name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 24.34.114.92
        username: daniel
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd ~/Server-Setup/ARTCC-Staffing-Update-Bot
          docker compose down
          git pull
          docker compose up --build -d
